---
sidebar: sidebar 
permalink: workflows/wf_create_backup.html 
keywords:  
summary:  
---
= Crie um backup para um aplicativo gerenciado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode criar um backup para um aplicativo gerenciado específico. Você pode usar o backup para restaurar ou clonar o aplicativo.



=== Antes de começar

Você deve ter o ID do aplicativo gerenciado para o qual deseja criar um backup. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste os aplicativos gerenciados"] para localizar o aplicativo.



=== 1. Crie uma cópia de segurança

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| POST | /Accounts/_id/k8s/v1/managedApps/_id/appBackups 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação gerida | Caminho | Sim | Identifica o aplicativo gerenciado onde o backup será criado. 


| JSON | Corpo | Sim | Fornece os parâmetros para o backup. Veja o exemplo abaixo. 
|===


===== Exemplo de entrada JSON

[source, json]
----
{
  "type": "application/astra-appBackup",
  "version": "1.0",
  "name": "backup-david-1"
}
----


===== Curl exemplo: Crie um backup para o aplicativo

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appBackups' --header 'Content-Type: application/astra-appBackup+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --d @JSONinput
----