---
sidebar: sidebar 
permalink: workflows/wf_create_snapshot.html 
keywords:  
summary:  
---
= Crie um instantâneo para um aplicativo gerenciado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode criar um snapshot para um aplicativo gerenciado específico.



=== Antes de começar

Você deve ter o ID do aplicativo gerenciado para o qual deseja criar um snapshot. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste os aplicativos gerenciados"] para localizar o aplicativo.



=== 1. Criar um instantâneo

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| POST | /Accounts/_id/k8s/v1/managedApps//appSnaps 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação gerida | Caminho | Sim | Identifica o aplicativo gerenciado onde o snapshot será criado. 


| JSON | Corpo | Sim | Fornece os parâmetros para o instantâneo. Veja o exemplo abaixo. 
|===


===== Exemplo de entrada JSON

[source, json]
----
{
  "type": "application/astra-appSnap",
  "version": "1.0",
  "name": "snapshot-david-1"
}
----


===== Curl exemplo: Crie um instantâneo para o aplicativo

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps' --header 'Content-Type: application/astra-appSnap+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --d @JSONinput
----