---
sidebar: sidebar 
permalink: workflows/wf_get_man_app.html 
keywords:  
summary:  
---
= Obtenha um aplicativo gerenciado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode recuperar todas as variáveis de recurso descrevendo um único aplicativo gerenciado.



=== Antes de começar

Você deve ter o ID do aplicativo gerenciado que deseja recuperar. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste os aplicativos gerenciados"] para localizar o aplicativo.



=== 1. Obtenha o aplicativo

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /Accounts/_id/k8s/v1/managedApps/_id 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação gerida | Caminho | Sim | Valor de ID do aplicativo gerenciado a ser recuperado. 
|===


===== Curl exemplo: Retorna todos os dados para o aplicativo

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----