---
sidebar: sidebar 
permalink: workflows/wf_list_man_apps.html 
keywords:  
summary:  
---
= Liste os aplicativos gerenciados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode listar as aplicações que atualmente são gerenciadas pelo Astra. Você pode fazer isso como parte de encontrar os snapshots ou backups de um aplicativo específico.



=== 1. Liste os aplicativos

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /Conta//k8s/v1/managedApps 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| incluir | Consulta | Não | Opcionalmente, selecione os valores que você deseja retornar na resposta. 
|===


===== Curl exemplo: Retorna todos os dados para todos os aplicativos

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl exemplo: Retorna o nome, id e estado de todos os aplicativos

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps?include=name,id,state' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemplo de saída JSON

[source, json]
----
{
  "items": [
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "running"
    ]
  ],
  "metadata": {}
}
----