---
sidebar: sidebar 
permalink: workflows/wf_list_snapshots.html 
keywords:  
summary:  
---
= Liste os instantâneos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode listar os snapshots que foram obtidos para um aplicativo gerenciado específico.



=== Antes de começar

Você deve ter o ID do aplicativo gerenciado para o qual deseja listar os snapshots. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste os aplicativos gerenciados"] para localizar o aplicativo.



=== 1. Liste os instantâneos

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /Accounts/_id/k8s/v1/managedApps//appSnaps 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="15,10,10,65"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação gerida | Caminho | Sim | Identifica o aplicativo gerenciado que possui os snapshots listados. 


| contar | Consulta | Não | Se `count=true` o número de instantâneos estiver incluído na seção metadados da resposta. 
|===


===== Curl exemplo: Retornar todos os snapshots para o aplicativo

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl exemplo: Retorna todos os instantâneos para o aplicativo e a contagem

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appSnaps?count=true' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemplo de saída JSON

[source, json]
----
{
  "items": [
    {
      "id": "dc2974ae-f71d-4c81-91b5-f96cf72dc3ba",
      "metadata": {
        "createdBy": "fb093413-b6fc-4a64-a48a-afc32ada8537",
        "creationTimestamp": "2021-06-04T21:23:14Z",
        "modificationTimestamp": "2021-06-04T21:23:14Z",
        "labels": []
      },
      "snapshotAppAsset": "4547658d-cc06-4c1d-ad8a-4a05274d0db0",
      "snapshotCreationTimestamp": "2021-06-04T21:23:47Z",
      "name": "test-postgres-app-snapshot-20210604212213",
      "state": "completed",
      "stateUnready": [],
      "type": "application/astra-appSnap",
      "version": "1.0"
    }
  ],
  "metadata": {
    "count": 1
  }
}
----