---
sidebar: sidebar 
permalink: workflows/wf_list_unman_apps.html 
keywords:  
summary:  
---
= Liste os aplicativos não gerenciados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode listar as aplicações que não são gerenciadas pelo Astra no momento. Você pode fazer isso como parte da seleção de um aplicativo a ser gerenciado.


NOTE: O endpoint REST usado nesses fluxos de trabalho retorna todas as aplicações Astra por padrão. Você pode usar o `filter` parâmetro de consulta na chamada API para solicitar que somente os aplicativos não gerenciados sejam retornados. Como alternativa, você pode omitir o parâmetro de filtro para retornar todos os aplicativos e examinar o `managedState` campo na saída para determinar quais aplicativos estão no `unmanaged` estado.



== Liste apenas os aplicativos com managedState igual a não gerenciados

Esse fluxo de trabalho usa o `filter` parâmetro de consulta para retornar apenas os aplicativos não gerenciados.



=== 1. Liste os aplicativos não gerenciados

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /Account//topology/v1/apps 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| filtro | Consulta | Não | Use um filtro para especificar quais aplicativos devem ser retornados. 


| incluir | Consulta | Não | Opcionalmente, selecione os valores que você deseja retornar na resposta. 
|===


===== Curl exemplo: Retorna o nome, id e managedState para os aplicativos não gerenciados

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?filter=managedState%20eq%20'unmanaged'&include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemplo de saída JSON

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ]
  ],
  "metadata": {}
}
----


== Liste todos os aplicativos e selecione os aplicativos não gerenciados

Esse fluxo de trabalho retorna todos os aplicativos. Você deve examinar a saída para determinar quais não são gerenciados.



=== 1. Liste todas as aplicações

Execute a seguinte chamada de API REST.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /Account//topology/v1/apps 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| incluir | Consulta | Não | Opcionalmente, selecione os valores que você deseja retornar na resposta. 
|===


===== Curl exemplo: Retorna todos os dados para todos os aplicativos

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl exemplo: Retorna o nome, id e managedState para todos os aplicativos

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Exemplo de saída JSON

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "mariadb-mariadb",
      "8da20fff-c69c-4170-bb0d-e4f91c5a1333",
      "managed"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ],
    [
      "davidns-postgres-app",
      "11e046b7-ec64-4184-85b3-debcc3b1da4d",
      "managed"
    ]
  ],
  "metadata": {}
}
----


=== 2. Selecione os aplicativos não gerenciados

Revise a saída da chamada API e selecione manualmente os aplicativos com `managedState` igual `unmanaged` a .
